apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "node-exporter-textfiles.fullname" . }}
  labels:
    {{- include "node-exporter-textfiles.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "node-exporter-textfiles.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "node-exporter-textfiles.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "node-exporter-textfiles.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      {{- range .Values.textfiles }}
        - name: {{ .name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          env:
            - name: SCRIPT
              value: "{{ .script }}"
            - name: OUTPUT_FILENAME
              value: {{ .outputFilename | quote }}
            - name: INTERVAL
              value: "{{ .interval }}"
            {{- with .additionalEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end}}
          volumeMounts:
            - mountPath: /var/lib/node_exporter
              name: textfile
            {{- with .additionalVolumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- toYaml .Values.additionalVolumes | nindent 8 }}
